"""RemoveUserIdUniqueConstraint

Revision ID: 8cac7f11d391
Revises: d9fa66e52d57
Create Date: 2023-08-05 23:58:20.197303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cac7f11d391'
down_revision = 'd9fa66e52d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('tasks_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_unique_constraint('tasks_user_id_key', ['user_id'])

    # ### end Alembic commands ###
